# Website settings
baseurl: "/"
url: "http://saptak.in"

# Internal nav
nav:
  main:
    blog: "/writing"
    #speaking: "/speaking"
    #projects: "/projects"
    #photos: "/photos"
  writing:
    all: "/writing"
    popular: "/writing/popular"
    tags: "/writing/tags"
    rss: "/feed.xml"

# Bio settings
name: "Saptak Sen"
slogan: "Programmer, entrepreneur, writer, speaker, traveler"
description: "The home page of Saptak Sen, product manager, author, and software engineer at Hortonworks and Microsoft."
thumbnail_path: "saptak_profile_med.jpg"
paypal_address: "http://paypal.me/saptak"
spark_book_url: "http://saptak.in/spark"
website_repo_url: "https://github.com/saptak/saptak.github.io"
hortonworks_url: "http://saptak.in/"

# URLs
contact_urls:
  twitter:
    url: "https://twitter.com/saptak"
    label: "Twitter"
    icon: "twitter-square"
    username: "@saptak"
  linkedin:
    url: "https://www.linkedin.com/in/saptak"
    label: "LinkedIn"
    icon: "linkedin-square"
  facebook:
    url: "https://www.facebook.com/saptak"
    label: "Facebook"
    icon: "facebook-square"
  google:
    url: "https://plus.google.com/+SaptakSen"
    label: "Google+"
    icon: "google-plus-square"
  slideshare:
    url: "https://www.slideshare.net/saptak"
    label: "SlideShare"
    icon: "slideshare"
  github:
    url: "https://github.com/saptak"
    label: "GitHub"
    icon: "github-square"
  email:
    url: "mailto:sen@ysaptak.in"
    label: "Email"
    value: "sen@saptak.in"
    icon: "envelope-square"

# Jekyll build settings
paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: coderay
timezone: 'America/Los_Angeles'
markdown: redcarpet

# Plugins (GitHub Pages only support a few)
gems:
  - jekyll-redirect-from
  - jekyll-sitemap

# redcarpet

redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
